name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - 'images.yaml'
      - '.github/workflows/*'
  pull_request:
    branches:
      - main
    paths:
      - 'images.yaml'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Sync Images
      uses: hhyasdf/image-sync-action@v1.1
      with:
        auth_file: ./auth.yaml
        images_file: ./images.yaml
        version: latest
        proc: 6
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
